#set up for Github workflow (happens on "Main" branch push: here we set up php, sql, migrate and run PhpUnit tests)
#PhpUnit test (biggest error were: 
                #error "LogicException: Invalid key supplied"  => because of missing Passport set up => php artisan passport:keys --force)
                #error 'SQLSTATE[HY000]: General error: 1 near "SET": syntax error (SQL: SET FOREIGN_KEY_CHECKS=0)' => because of using SQLLite
name: Laravel

on:
  push:
    branches: [ main ]  # Trigger on push to main branch   - '**'  # This will trigger the action for pushes to any branch
  pull_request:
    branches: [ main ]

jobs:
  
  # Job 1 (Pest tests and codesniffer). It is run in CI & has nothing to do with Dockerfile & docker-compose.yml --------------------
  job_1_my-pest-tests:      #job ID

    runs-on: ubuntu-latest
    
    services:
      # init SQL container (check version) *********
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
          MYSQL_USER: user1
          MYSQL_PASSWORD: userpassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin --user=root --password=password ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      # end  init SQL container *******
      
      
    steps:
    - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access i
    
    # Set up PHP version (check version)-------------------
    - name: Set up PHP 8.4.8
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4.8' # fix here ->Specify the PHP version here
        coverage: xdebug      # Optional: Enable coverage with Xdebug
    # End Set up PHP
    
    #Copy env, makes a copy of '.env.example' & rename it to '.env', as '.env' is under Git ignore (not uploaded to github) ------------------------------
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    # Install Dependencies ------------------
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress
    - name: Generate laravel key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    #
    #- name: Create Database
      #run: |
        #mysql -u user1 -p${{ 'password' }} -h 127.0.0.1 -e "CREATE DATABASE IF NOT EXISTS laravel_2024_migration_testing;"
      #run: |
        #mkdir -p database
        #touch database/database.sqlite
        
    #Compile js asserts -------------------
    - name: Compile assets
      run: |
        npm install
        npm run build # version for laravel 12  #version for laravel 6 => #npm run production
        
    #Set up environment for testing -------
    #copies the contents of the .env.testing file into .env. This is often used when you want your Laravel application to temporarily use the testing configuration as its main environment setup.
    - name: Set up environment for testing
      run: cp .env.testing .env
      
    #get sql ready ------------------------
    - name: Wait for MySQL service to be ready
      run: |
          for i in {30..0}; do
            if mysqladmin ping --host=127.0.0.1 --port=3306 --user=root --password=root_password --silent; then
              break
            fi
            echo 'Waiting for MySQL to start...'
            sleep 1
          done
          
    # Run database migrations -------------
    - name: Run database migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1  # Assuming MySQL is on the same container
        DB_PORT: 3306
        DB_DATABASE: laravel
        DB_USERNAME: user1         #does not matter what u have in .env, as .env is not on github & created from .env.example in this CI
        DB_PASSWORD: userpassword  # Replace with the correct password or leave empty if not used
      run: php artisan migrate --force  # --force is required to run in CI environment
      
    #Run Pest tests   -------------------
    - name: Execute Pest tests (Unit and Feature tests) 
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1  # Assuming MySQL is on the same container
        DB_PORT: 3306
        DB_DATABASE: laravel
        DB_USERNAME: user1
        DB_PASSWORD: userpassword   # Replace with the correct password or leave empty if not used
      run: |
        php artisan config:cache --env=testing                 #set up for testing
        #php artisan migrate --env=testing --force    
        #php artisan passport:client --personal --name=SomeName #generate Passport personal token
        #php artisan passport:install                           #Passport install
        #php artisan passport:keys --force         
        #php artisan db:disable-foreign-key   # we do it in prev step
        ./vendor/bin/pest   #run pest
        
     # Run Php Codesniffer check, so far we check /routes only (set in phpcs.xml.dist) (if want can run as a separated job) -------------
     #- name: Run Php Codesniffer check
     # run: composer codesniffer-check  # this command is set in composer.json, same as "php vendor/bin/phpcs"
      
   





   
   
  #---------------------------------------------------------------------------------------------------------------------------
  # Job 2(run PhpStan static analysis as a separated job. If want can run as in Job 1)
  job_2_phpstan-static-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4.8
      - name: Install dependencies
        run: composer install
      - name: Run PhpStan static 
        run: ./vendor/bin/phpstan analyse
        
   

   
   # Job-3 (test docker-compose.yml & Dockerfile are working, check php/apache & sql containers) ---------------------------------------------------
  job_3_test-sail-docker-compose-yml-images-build-and-run-containers:
    runs-on: ubuntu-latest

    
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4.8
          extensions: mbstring, pdo, mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Copy .env
        run: cp .env.example .env

      - name: Run sail
        run: ./vendor/bin/sail up -d

      - name: Generate application key
        run: ./vendor/bin/sail artisan key:generate

       # Some general tests to if php/apache containers is OK, see output in github/actions
      - name: test if Php/apache Docker Sail container  is OK
        run: |
          #test php version, 
          ./vendor/bin/sail php -v

          #see folder structure 
          ./vendor/bin/sail shell -c "ls -la"   



          #test if console command is running, returns 'phone is 115'
          ./vendor/bin/sail php artisan quiz:start -v


      # migrations were crashing without it
      - name: Wait for MySQL to be ready
        run: |
          ./vendor/bin/sail exec mysql bash -c 'until mysqladmin ping -h"mysql" --silent; do sleep 1; done'

      #Compile js asserts, as some tests will crash without it-------------------
      - name: Compile js asserts 
        run: |
          ./vendor/bin/sail npm install
          ./vendor/bin/sail npm run build # version for laravel 12  #version for laravel 6 => #npm run production

      - name: Run migrations
        run: ./vendor/bin/sail artisan migrate --force

      - name: Run tests (Pest or PHPUnit)
        run: ./vendor/bin/sail pest
    




  # Job-5 deploy one file 'last-deploy-info.php' to alwaysdata.com to folder/MyFilament_Laravel12  ---------------------------------------------------
  job_5_deploy_one_test_file:
    runs-on: ubuntu-latest
    needs: [job_1_my-pest-tests, job_2_phpstan-static-check, job_3_test-sail-docker-compose-yml-images-build-and-run-containers]  #will run only after these jobs
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy file to remote server via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  #github secrets
          REMOTE_HOST: ${{ secrets.SSH_HOST }}             #github secrets
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_PATH: www/MyFilament_Laravel12      #/path/on/remote/server/
        run: |
          # Create SSH directory and add private key
          mkdir -p ~/.ssh                               #Creates a local .ssh folder on the GitHub runner.
          cho "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa       #Saves the private key from secrets into a file
          chmod 600 ~/.ssh/id_rsa                       #Secures the key with proper file permissions (600).

          # Add remote host to known_hosts to avoid prompt
          ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts
          
          
          #create file last-deploy-info.php which contains current timestamp  dd-mm-yy hh::mm::ss
          echo "<?php echo 'Filament Deployed at  $(TZ='Europe/Kyiv' date -d '-1 hour' '+%d-%m-%y %H:%M:%S')'; ?>" >> last-deploy-info.php #creates a file 'last-deploy-info.php' with current time - 1 hour , >> appends content to file , not overwrite, but since it is a new created in github ci, it always creates a new file

          # Variant.1 Use scp to copy the file last-deploy-info.php to the remote server (works).  If exists already, it overwrite it 
          scp last-deploy-info.php $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH   #goes to => https://dima.alwaysdata.net/last-deploy-info.php
          
          # Variant.2 Instead of creating new file, append content to existing
          
          #Conditionally copy deploy.php via SSH, only if does not exitst already
          #ssh "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "test -e '${{ secrets.REMOTE_PATH }}/deploy.php'" || scp deploy.php "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.REMOTE_PATH }}"

          #append content
          #cat deploy.php | ssh "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "cat >> '${{ secrets.REMOTE_PATH }}/deploy.php'"

          
          # Use scp to copy the README.md file to the remote server (works)
          #scp README.md $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH   #goes to => https://dima.alwaysdata.net/README.md
          
          
  

  # Job-7  send notification "Deploy successful" to telegram  ---------------------------------------------------
  job_7_notify_in_telegram:
    runs-on: ubuntu-latest
    needs: [job_1_my-pest-tests, job_2_phpstan-static-check, job_3_test-sail-docker-compose-yml-images-build-and-run-containers, job_5_deploy_one_test_file]  #will run only after these jobs

    steps:
      - name: Send message to Telegram
        if: success()  #Run this job only if all previous jobs have succeeded."
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}  #github secrets
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}   #github secrets
        run: |
          MESSAGE="✅ CI/CD on Filament 12 completed successfully on branch $GITHUB_REF"   #U+1F680 is UTF-8 for "rocket-icon".
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
            -d chat_id=$TELEGRAM_CHAT_ID \
            -d text="$MESSAGE" \
            -d parse_mode=Markdown
   
      - name: Notify Telegram on Failure
        if: failure()  # only run if previous job failed
        run: |
          MESSAGE="❌ CI/CD on Filament 12 failed on branch $GITHUB_REF"     #U+274C  UTF-8 for "red cross".
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
            -d chat_id=$TELEGRAM_CHAT_ID \
            -d text="$MESSAGE" \
            -d parse_mode=Markdown




   
        
  # Job-6 Deploy somewhere (for example to AWS) ---------------------------------------------------
  # Authenticate to the the server via ssh 
  # and run our deployment script
  
  #job_6_deploy_to_cloud:
    #runs-on: ubuntu-latest
    #needs: [job_1_my-phpunit-tests, job_2_psalm-static-check, job_3_test-docker-compose-yml-images-build-and-run-containers, job_4_codesniffer-check]  #will run only after these jobs
    
    #steps:
      #- uses: actions/checkout@v2
      #- name: Deploy to server
        #uses: appleboy/ssh-action@master
        #with:
          #host: ${{ secrets.HOST }}
          #username: ${{ secrets.USERNAME }}
          #port: ${{ secrets.PORT }}
          #key: ${{ secrets.SSHKEY }}
          ##script: "cd /var/www/html && ./.scripts/deploy.sh"
          #run: | 
            
            #set -e                         #When you use set -e, the script stops running as soon as any command fails.     #!/bin/bash

            #echo "Deployment started ..."
            
            #(php artisan down) || true    # Enter maintenance mode or return true, if already is in maintenance mode

            #git pull origin production    # Pull the latest version of the app

            #composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader   # Install composer dependencies

            #php artisan clear-compiled     # Clear the old cache

            #php artisan optimize           # Recreate cache

            #npm run prod                   # Compile npm assets

            #php artisan migrate --force    # Run database migrations

            #php artisan up                 # Exit maintenance mode

            #echo "Deployment finished!"